services:
  - type: web
    name: gsk-link-finder
    env: docker
    repo: https://github.com/akashvishwakarma27/links-management-tool.git
    rootDir: backend
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_VERSION
        value: 17
